Repository PROJECT-BLOB/front-end, pull requests merged in 2024-05, with the labels that each got.

#62 회원가입 진행 중
  apis/axios.ts
  apis/oauth/getOAuthData.ts
  apis/user/sign/createUser.ts
  app/map/_hooks/useCreateUserForm.ts
  app/oauth/[provider]/page.tsx
  app/signin/page.tsx
  components/Input/Input.module.scss
  components/Input/Input.tsx
  components/Modal/CreateUser/CreateUser.module.scss
  components/Modal/CreateUser/CreateUser.tsx
  components/Modal/Modal.module.scss
  next.config.mjs
  stores/useModalStore.ts
  stores/useOAuthStore.ts
  stores/useTokenStore.ts
Labels: Task, 기능구현, 버그, 퍼블리싱

#64 post 모달 작업 중간점검
  app/testmap/page.tsx
  components/Button/BlobButton.module.scss
  components/Button/BlobButton.tsx
  components/Button/Button.stories.tsx
  components/Modal/Modal.module.scss
  components/Modal/Modal.tsx
  components/Modal/ReadPost/ReadPost.module.scss
  components/Modal/ReadPost/ReadPost.tsx
  components/Modal/WritePost/CloseHeader.module.scss
  components/Modal/WritePost/CloseHeader.tsx
  components/Modal/WritePost/ContentInput.module.scss
  components/Modal/WritePost/ContentInput.tsx
  components/Modal/WritePost/ImageInput.tsx
  components/Modal/WritePost/TitleInput.module.scss
  components/Modal/WritePost/TitleInput.tsx
  components/Modal/WritePost/WritePost.module.scss
  components/Modal/WritePost/WritePost.tsx
  hooks/useUploadImage.ts
  public/icons/upload-01.svg
  styles/global-styles/_mixin.scss
  styles/global-styles/_variable.scss
Labels: Task, 기능구현, 퍼블리싱

#63 조회모달 기능 구현
  apis/post/creatReply.ts
  apis/post/createComment.ts
  apis/post/deleteComment.ts
  apis/post/getCommentList.ts
  apis/post/getReplyList.ts
  apis/post/postBookmark.ts
  apis/post/postCommentLike.ts
  apis/post/postPostLike.ts
  apis/user/mypage/getUserCommentList.ts
  app/map/page.tsx
  components/CategoryBox.module.scss
  components/CategoryBox.tsx
  components/Kebab.module.scss
  components/Kebab.tsx
  components/Modal/ReadPost/Comment.module.scss
  components/Modal/ReadPost/Comment.tsx
  components/Modal/ReadPost/CommentBox.module.scss
  components/Modal/ReadPost/CommentBox.tsx
  components/Modal/ReadPost/ImageContainer.module.scss
  components/Modal/ReadPost/MainContainer.module.scss
  components/Modal/ReadPost/MainContainer.tsx
  components/Modal/ReadPost/ProfileContainer.module.scss
  components/Modal/ReadPost/ProfileContainer.tsx
  components/Modal/ReadPost/ReadPost.module.scss
  components/Modal/ReadPost/ReadPost.tsx
  components/Modal/ReadPost/Reply.module.scss
  components/Modal/ReadPost/Reply.tsx
  components/Modal/ReadPost/ReplyBox.tsx
  components/Tab.module.scss
  components/Tab.tsx
  public/icons/filled-red-heart.svg
  types/Post.ts
Labels: Epic, Task, 기능구현

#68 마이페이지 퍼블리싱 중...
  apis/user/mypage/getUserDetail.ts
  app/mypage/_components/UserProfile/UserProfile.module.scss
  app/mypage/_components/UserProfile/UserProfile.tsx
  app/mypage/myPage.module.scss
  app/mypage/page.tsx
  components/Avatar/Avatar.module.scss
  components/Avatar/Avatar.tsx
  components/Input/Input.tsx
  public/icons/check-heart.svg
  queries/keys/userQueryKeys.ts
  queries/useUserQueries.ts
  styles/global-styles/global.scss
  types/.gitkeep
  types/User.ts
Labels: 퍼블리싱

#72 지도페이지 1차 필터링 컴포넌트 제작
  .storybook/main.ts
  .storybook/preview.ts
  components/Category/CategoryFiltering.module.scss
  components/Category/CategoryFiltering.tsx
  components/Modal/ReadPost/ReadPost.tsx
  package-lock.json
  package.json
  public/icons/atom-02.svg
  public/icons/chevron-right.svg
  public/icons/magic-wand-02-2.svg
  public/icons/signal-02-2.svg
  public/icons/thumbs-down-orange.svg
  public/icons/thumbs-up-red.svg
  stories/CategoryFiltering.stories.tsx
Labels: 퍼블리싱

#70 모달 구조 변경
  app/map/page.tsx
  components/Modal/Modal.module.scss
  components/Modal/Modal.tsx
  components/Modal/ReadPost/CommentBox.module.scss
  components/Modal/ReadPost/ImageContainer.module.scss
  components/Modal/ReadPost/MainContainer.module.scss
  components/Modal/ReadPost/MainContainer.tsx
  components/Modal/ReadPost/ReadPost.module.scss
  components/Modal/ReadPost/ReadPost.tsx
  stores/useModalStore.ts
  styles/global-styles/_media-breakpoint.scss
Labels: 리팩토링

#75 GNB 컴포넌트 작성
  .stylelintrc
  app/RootLayout.module.scss
  app/layout.tsx
  components/Avatar/Avatar.tsx
  components/Button/CreatePostButton.module.scss
  components/Button/CreatePostButton.tsx
  components/GlobalNavigationBar/AlarmIcon.tsx
  components/GlobalNavigationBar/GlobalNavigationBar.module.scss
  components/GlobalNavigationBar/GlobalNavigationBar.tsx
  components/GlobalNavigationBar/MenuBar.module.scss
  components/GlobalNavigationBar/MenuBar.tsx
  components/GlobalNavigationBar/NavigationTab.tsx
  components/GlobalNavigationBar/NavigationTabs.module.scss
  components/GlobalNavigationBar/TabItem.module.scss
  components/GlobalNavigationBar/TabItem.tsx
  components/Modal/ReadPost/ReadPost.tsx
  components/shared/Logo.module.scss
  components/shared/Logo.tsx
  public/icons/bell-alarm-24.svg
  public/icons/bell-default-24.svg
  public/icons/ellipse-63.svg
  public/icons/line-79.svg
  public/icons/plus.svg
  public/icons/user-24.svg
  styles/global-styles/_media-breakpoint.scss
  styles/global-styles/global.scss
  styles/global-styles/reset.scss
Labels: Task, 기능구현, 퍼블리싱

#76 기능들 react-query로 연결 해 주었습니다.
  apis/post/creatReply.ts
  apis/post/createComment.ts
  apis/post/createPost.ts
  apis/post/getPostList.ts
  apis/post/postReportComment.ts
  apis/post/postReportPost.ts
  apis/post/updateCommentLike.ts
  apis/post/updatePostLike.ts
  app/map/page.tsx
  app/signin/page.tsx
  components/CategoryBox.module.scss
  components/CategoryBox.tsx
  components/Kebab.module.scss
  components/Kebab.tsx
  components/Modal/CreateUser/CreateUser.tsx
  components/Modal/ModalContainer.module.scss
  components/Modal/ModalContainer.tsx
  components/Modal/ReadPost/Comment.tsx
  components/Modal/ReadPost/CommentBox.module.scss
  components/Modal/ReadPost/CommentBox.tsx
  components/Modal/ReadPost/ImageContainer.module.scss
  components/Modal/ReadPost/ImageContainer.tsx
  components/Modal/ReadPost/MainContainer.module.scss
  components/Modal/ReadPost/MainContainer.tsx
  components/Modal/ReadPost/ProfileContainer.module.scss
  components/Modal/ReadPost/ProfileContainer.tsx
  components/Modal/ReadPost/ReadPost.module.scss
  components/Modal/ReadPost/ReadPost.tsx
  components/Modal/ReadPost/Reply.tsx
  components/Modal/ReadPost/hooks/useImageControl.ts
  components/Modal/ReadPost/hooks/useKebabState.ts
  components/Modal/WritePost/WritePost.tsx
  next.config.mjs
  public/icons/filled-image-index.svg
  public/icons/image-index.svg
  public/icons/next-button.svg
  public/icons/previous-button.svg
  queries/usePostQueries.ts
  stores/useModalStore.ts
  styles/global-styles/global.scss
  types/Post.ts
Labels: Epic, Task, 기능구현

#77 마이페이지 퍼블리싱 완료
  apis/axios.ts
  apis/oauth/getOAuthData.ts
  apis/user/mypage/getUserDetail.ts
  apis/user/sign/createUser.ts
  app/layout.tsx
  app/map/_hooks/useCreateUserForm.ts
  app/mypage/_components/Post/PostItem.module.scss
  app/mypage/_components/Post/PostItem.tsx
  app/mypage/_components/Post/PostList.module.scss
  app/mypage/_components/Post/PostList.tsx
  app/mypage/_components/UpdateProfileModal/UpdateProfileModal.module.scss
  app/mypage/_components/UpdateProfileModal/UpdateProfileModal.tsx
  app/mypage/_components/UserProfile/UserProfile.module.scss
  app/mypage/_components/UserProfile/UserProfile.tsx
  app/mypage/myPage.module.scss
  app/mypage/page.tsx
  app/oauth/[provider]/page.tsx
  app/signin/page.tsx
  components/Avatar/Avatar.module.scss
  components/Checkbox/Checkbox.module.scss
  components/Input/Input.module.scss
  components/Input/Input.tsx
  components/Modal/CreateUser/CreateUser.tsx
  components/Modal/ModalContainer.tsx
  public/icons/message-circle-02.svg
  queries/keys/userQueryKeys.ts
  queries/useUserQueries.ts
  stores/useModalStore.ts
  stores/useOAuthStore.ts
  stores/userStore.ts
  styles/global-styles/_align.scss
  types/User.ts
Labels: Task, 버그, 퍼블리싱

#78 무한스크롤 api 연결 & 리팩토링
  apis/post/getCommentList.ts
  apis/post/getFeed.ts
  apis/user/mypage/testPost.ts
  app/feed/Feed.module.scss
  app/feed/page.tsx
  components/Kebab.tsx
  components/Modal/ReadPost/CommentBox.tsx
  components/Modal/ReadPost/ReadPost.tsx
  constants/pageValues.ts
  queries/useInfiniteQueries.ts
  queries/useInfiniteScrollQuery.ts
  queries/usePostQueries.ts
  stories/Tab.stories.ts
Labels: 기능구현, 리팩토링

#80 회원가입 유효성 검사, 내가 쓴 글 목록 불러오기
  apis/user/mypage/getUserBookmarkList.ts
  apis/user/mypage/getUserCommentList.ts
  apis/user/mypage/getUserPostList.ts
  apis/user/sign/checkBlobId.ts
  app/RootLayout.module.scss
  app/map/_hooks/useCreateUserForm.ts
  app/mypage/_components/Comment/CommentItem.tsx
  app/mypage/_components/Post/PostItem.module.scss
  app/mypage/_components/Post/PostItem.tsx
  app/mypage/_components/Post/PostList.tsx
  app/mypage/_components/Tab/TabItem.tsx
  app/mypage/_components/Tab/TabList.module.scss
  app/mypage/_components/Tab/TabList.tsx
  app/mypage/_components/UserProfile/UserProfile.tsx
  app/mypage/myPage.module.scss
  app/mypage/page.tsx
  app/signin/_components/RegisterModal/RegisterModal.module.scss
  app/signin/_components/RegisterModal/RegisterModal.tsx
  app/signin/_components/SigninButton/SigninButton.module.scss
  app/signin/_components/SigninButton/SigninButton.tsx
  app/signin/page.tsx
  components/Input/Input.module.scss
  components/Input/Input.tsx
  components/Modal/ModalContainer.tsx
  components/SignInput/SignInput.module.scss
  components/SignInput/SignInput.tsx
  queries/usePostQueries.ts
  stores/useTabStore.ts
  styles/global-styles/global.scss
  utils/registerOptions.tsx
Labels: Task, 기능구현, 버그

#79 모달 변경
  apis/post/createComment.ts
  app/RootLayout.module.scss
  app/layout.tsx
  app/map/page.tsx
  app/mypage/_components/UserProfile/UserProfile.tsx
  app/signin/page.tsx
  components/GlobalNavigationBar/GlobalNavigationBar.module.scss
  components/Kebab.module.scss
  components/Modal/ModalContainer.tsx
  components/Modal/ReadPost/ReadPost.tsx
  components/Portal.tsx
  stores/useModalStore.ts
Labels: 리팩토링

#82 공용으로 사용할 수 있도록 input 컴포넌트 분리& 버그픽스
  apis/user/mypage/getUserBookmarkList.ts
  apis/user/mypage/getUserPostList.ts
  apis/user/sign/checkBlobId.ts
  app/mypage/_components/Post/PostItem.module.scss
  app/mypage/_components/Post/PostItem.tsx
  app/mypage/_components/Post/PostList.tsx
  app/mypage/_components/UserProfile/UserProfile.module.scss
  app/mypage/_components/UserProfile/UserProfile.tsx
  app/mypage/page.tsx
  app/oauth/[provider]/page.tsx
  app/signin/Signin.module.scss
  app/signin/_components/RegisterModal/RegisterModal.module.scss
  app/signin/_components/RegisterModal/RegisterModal.tsx
  app/signin/_components/SignInput/SignInput.module.scss
  app/signin/_components/SignInput/SignInput.tsx
  app/signin/_components/SigninButton/SigninButton.tsx
  app/signin/_hooks/useCreateUserForm.ts
  app/signin/page.tsx
  components/Avatar/Avatar.tsx
  components/Button/BlobButton.module.scss
  components/Button/BlobButton.tsx
  components/Checkbox/Checkbox.module.scss
  components/Input/Input.module.scss
  components/Input/Input.tsx
  components/RadioButton/Radio.module.scss
  components/RadioButton/Radio.tsx
  components/RadioButton/RadioGroup.tsx
  components/SignInput/SignInput.tsx
  constants/redirectUrls.ts
  queries/usePostQueries.ts
  types/Errors.ts
  types/Input.ts
  utils/.gitkeep
  utils/registerOptions.tsx
Labels: Task, 기능구현, 퍼블리싱

#89 모달 인풋 제작 + autocomplete City props 작성
  app/maptest/AutoComplete.module.scss
  app/maptest/AutoCompleteCity.tsx
  app/maptest/page.tsx
  components/Button/BlobButton.module.scss
  components/Button/BlobButton.tsx
  components/ImageUploader.module.scss
  components/ImageUploader.tsx
  components/Modal/WritePost/CloseHeader.module.scss
  components/Modal/WritePost/CloseHeader.tsx
  components/Modal/WritePost/ContentInput.module.scss
  components/Modal/WritePost/ImageInput.tsx
  components/Modal/WritePost/PositionDetail.tsx
  components/Modal/WritePost/TitleInput.module.scss
  components/Modal/WritePost/TitleInput.tsx
  components/Modal/WritePost/WritePost.module.scss
  components/Modal/WritePost/WritePost.tsx
Labels: Task, 기능구현, 퍼블리싱

#90 [피드페이지] 퍼블리싱 및 데이터 정렬, 키워드 검색, 카테고리 삭제 기능 구현
  apis/post/creatReply.ts
  apis/post/createComment.ts
  apis/post/createPost.ts
  apis/post/deletePost.ts
  apis/post/getCommentList.ts
  apis/post/getFeed.ts
  apis/post/getPost.ts
  apis/post/getPostList.ts
  apis/post/updateBookmark.ts
  apis/post/updateCommentReport.ts
  apis/post/updatePostReport.ts
  app/feed/Feed.module.scss
  app/feed/page.tsx
  app/mypage/_components/Comment/CommentItem.tsx
  app/mypage/_components/Post/PostItem.module.scss
  app/mypage/_components/Post/PostItem.tsx
  app/mypage/_components/Post/PostList.module.scss
  app/mypage/_components/Post/PostList.tsx
  app/mypage/page.tsx
  components/CategoryBox.module.scss
  components/CategoryBox.tsx
  components/Kebab.module.scss
  components/Kebab.tsx
  components/Modal/ReadPost/CommentBox.tsx
  components/Modal/ReadPost/CommentContainer.module.scss
  components/Modal/ReadPost/CommentContainer.tsx
  components/Modal/ReadPost/ImageContainer.tsx
  components/Modal/ReadPost/MainContainer.tsx
  components/Modal/ReadPost/hooks/useImageControl.ts
  public/icons/category-x.svg
  public/icons/search-icon-gray.svg
  public/icons/settings-04.svg
  queries/useInfiniteScrollQuery.ts
  queries/usePostQueries.ts
  types/Post.ts
  utils/calculateTimeWhenItWillDisappear.ts
Labels: Epic, Task, 기능구현

#95 피드페이지 모달 & 카테고리 퍼블리싱
  app/feed/_components/FilteringModal/FilteringModal.module.scss
  app/feed/_components/FilteringModal/FilteringModal.tsx
  app/feed/page.tsx
  components/Category/CategoryFiltering.module.scss
  components/Category/CategoryFiltering.tsx
  components/Category/SubCategoryFiltering.module.scss
  components/Category/SubCategoryFiltering.tsx
  components/Modal/ModalContainer.tsx
  components/Modal/WritePost/WritePost.tsx
  public/fonts/ibm-plex-sans-kr/IBM_Plex_Sans_KR.css
  stores/useModalStore.ts
  stories/CategoryFiltering.stories.tsx
  stories/SubCategoryFiltering.stories.tsx
Labels: 기능구현, 퍼블리싱

#94 프로필 수정 모달 퍼블리싱, 린트 에러 해결
  apis/user/mypage/getUserCommentList.ts
  apis/user/mypage/updateNickname.ts
  apis/user/mypage/updateProfileImage.ts
  apis/user/mypage/updateProfileVisibility.ts
  apis/user/mypage/updateUserProfile.ts
  apis/user/sign/createUser.ts
  app/feed/page.tsx
  app/mypage/_components/Comment/CommentItem.tsx
  app/mypage/_components/Post/PostList.tsx
  app/mypage/_components/UpdateProfileModal/UpdateProfileModal.module.scss
  app/mypage/_components/UpdateProfileModal/UpdateProfileModal.tsx
  app/mypage/_components/UserProfile/UserProfile.tsx
  app/mypage/_hooks/useUpdateUserForm.ts
  app/mypage/page.tsx
  app/signin/_components/RegisterModal/RegisterModal.module.scss
  app/signin/_components/SignInput/SignInput.tsx
  app/signin/_hooks/useCreateUserForm.ts
  components/Avatar/Avatar.module.scss
  components/Button/MonoButton.module.scss
  components/Button/MonoButton.tsx
  components/Input/Input.module.scss
  components/Input/Input.tsx
  components/Input/TextArea.tsx
  components/Modal/ModalContainer.module.scss
  components/Post/PostItem.module.scss
  components/Post/PostItem.tsx
  components/Post/PostList.module.scss
  components/Post/PostList.tsx
  queries/usePostQueries.ts
  styles/global-styles/_align.scss
  types/Input.ts
  types/User.ts
  utils/registerOptions.tsx
Labels: 리팩토링, 퍼블리싱

#96 조회 모달 바뀐 디자인으로 변경
  apis/post/getReplyList.ts
  app/feed/Feed.module.scss
  app/feed/page.tsx
  components/Modal/ReadPost/Body/Image/ImageContainer.module.scss
  components/Modal/ReadPost/Body/Image/ImageContainer.tsx
  components/Modal/ReadPost/Body/Main/Comment/CommentBox.module.scss
  components/Modal/ReadPost/Body/Main/Comment/CommentBox.tsx
  components/Modal/ReadPost/Body/Main/Comment/CommentContainer.module.scss
  components/Modal/ReadPost/Body/Main/Comment/CommentContainer.tsx
  components/Modal/ReadPost/Body/Main/Comment/CommentSubmitForm.module.scss
  components/Modal/ReadPost/Body/Main/Comment/CommentSubmitForm.tsx
  components/Modal/ReadPost/Body/Main/Comment/Reply.module.scss
  components/Modal/ReadPost/Body/Main/Comment/Reply.tsx
  components/Modal/ReadPost/Body/Main/MainContainer.module.scss
  components/Modal/ReadPost/Body/Main/MainContainer.tsx
  components/Modal/ReadPost/Body/Main/ProfileContainer.module.scss
  components/Modal/ReadPost/Body/Main/ProfileContainer.tsx
  components/Modal/ReadPost/Body/ReadPostBody.module.scss
  components/Modal/ReadPost/Body/ReadPostBody.tsx
  components/Modal/ReadPost/CommentBox.module.scss
  components/Modal/ReadPost/CommentBox.tsx
  components/Modal/ReadPost/Header/ReadPostHeader.module.scss
  components/Modal/ReadPost/Header/ReadPostHeader.tsx
  components/Modal/ReadPost/MainContainer.module.scss
  components/Modal/ReadPost/MainContainer.tsx
  components/Modal/ReadPost/ProfileContainer.tsx
  components/Modal/ReadPost/ReadPost.module.scss
  components/Modal/ReadPost/ReadPost.tsx
  components/Post/PostItem.tsx
  components/Post/PostList.module.scss
  components/Post/PostList.tsx
  public/icons/timeblob-info.svg
  queries/useInfiniteScrollQuery.ts
  queries/usePostQueries.ts
  stores/useModalStore.ts
  utils/calculateDisappearTime.ts
Labels: 리팩토링, 퍼블리싱

#98 제목, 내용 hook-form으로 전송
  apis/post/createPost.ts
  app/map/_hooks/useCreateForm.ts
  app/maptest/_deprecated/AutoCompleteCity.tsx
  components/ImageUploader.module.scss
  components/ImageUploader.tsx
  components/Input/Input.tsx
  components/Modal/WritePost/ContentInput.module.scss
  components/Modal/WritePost/ContentInput.tsx
  components/Modal/WritePost/PostModalInput.module.scss
  components/Modal/WritePost/PostModalInput.tsx
  components/Modal/WritePost/TitleInput.module.scss
  components/Modal/WritePost/TitleInput.tsx
  components/Modal/WritePost/WritePost.module.scss
  components/Modal/WritePost/WritePost.tsx
  hooks/useUploadImage.ts
  public/icons/upload-image.svg
Labels: Task, 기능구현

#99 조회 모달 신고 및 삭제 연결 및 자잘한 버그? 수정
  apis/post/updatePostReport.ts
  components/CategoryBox.tsx
  components/Input/Input.module.scss
  components/Kebab.tsx
  components/Modal/ModalContainer.tsx
  components/Modal/ReadPost/Body/Image/ImageContainer.module.scss
  components/Modal/ReadPost/Body/Image/ImageContainer.tsx
  components/Modal/ReadPost/Body/Main/Comment/CommentBox.module.scss
  components/Modal/ReadPost/Body/Main/Comment/CommentBox.tsx
  components/Modal/ReadPost/Body/Main/Comment/CommentContainer.module.scss
  components/Modal/ReadPost/Body/Main/Comment/CommentContainer.tsx
  components/Modal/ReadPost/Body/Main/Comment/CommentSubmitForm.module.scss
  components/Modal/ReadPost/Body/Main/Comment/CommentSubmitForm.tsx
  components/Modal/ReadPost/Body/Main/Comment/Reply.module.scss
  components/Modal/ReadPost/Body/Main/Comment/Reply.tsx
  components/Modal/ReadPost/Body/Main/MainContainer.module.scss
  components/Modal/ReadPost/Body/Main/MainContainer.tsx
  components/Modal/ReadPost/Body/Main/ProfileContainer.tsx
  components/Modal/ReadPost/Header/ReadPostHeader.module.scss
  components/Modal/ReadPost/Header/ReadPostHeader.tsx
  components/Modal/ReadPost/ReadPost.module.scss
  components/Modal/WritePost/WritePost.module.scss
  package-lock.json
  package.json
  public/icons/filled-image-index.svg
  public/icons/image-index.svg
  public/icons/next-button.svg
  public/icons/previous-button.svg
  queries/usePostQueries.ts
  stores/useModalStore.ts
  styles/global-styles/font.scss
  styles/global-styles/global.scss
Labels: 리팩토링, 버그

#100 쿼리키 리팩토링, css 수정
  apis/user/checkNickName.ts
  apis/user/mypage/updateUserProfile.ts
  apis/user/updateBio.ts
  app/mypage/_components/Comment/CommentItem.tsx
  app/mypage/_components/UpdateProfileModal/UpdateProfileModal.module.scss
  app/mypage/_components/UpdateProfileModal/UpdateProfileModal.tsx
  app/mypage/_hooks/useUpdateUserProfileForm.ts
  app/signin/_components/RegisterModal/RegisterModal.module.scss
  app/signin/_components/SignInput/SignInput.module.scss
  components/Avatar/Avatar.tsx
  components/Button/MonoButton.module.scss
  components/IconTag/IconTag.module.scss
  components/IconTag/IconTag.tsx
  components/Post/PostItem.module.scss
  components/Post/PostItem.tsx
  public/icons/check-heart-white.svg
  queries/keys/userQueryKeys.ts
  queries/useUserQueries.ts
  utils/registerOptions.tsx
Labels: 리팩토링, 퍼블리싱

#101 폴더구조 변경 및 폰트 문제 해결
  apis/post/updatePostReport.ts
  app/feed/[postId]/feedPost.module.scss
  app/feed/[postId]/page.tsx
  app/feed/page.tsx
  app/map/_components/ReadPostModal.module.scss
  app/map/_components/ReadPostModal.tsx
  components/CategoryBox.tsx
  components/Input/Input.module.scss
  components/Kebab.tsx
  components/Modal/ModalContainer.module.scss
  components/Modal/ModalContainer.tsx
  components/Modal/ReadPost/Body/Main/Comment/CommentSubmitForm.module.scss
  components/Modal/ReadPost/Body/Main/MainContainer.tsx
  components/Modal/ReadPost/Body/ReadPostBody.module.scss
  components/Modal/ReadPost/Body/ReadPostBody.tsx
  components/Modal/ReadPost/ReadPost.tsx
  components/Modal/WritePost/WritePost.module.scss
  components/Post/PostItem.module.scss
  components/Post/PostItem.tsx
  components/Post/PostList.tsx
  components/ReadPost/Header/ReadPostHeader.module.scss
  components/ReadPost/Header/ReadPostHeader.tsx
  components/ReadPost/Image/ImageContainer.module.scss
  components/ReadPost/Image/ImageContainer.tsx
  components/ReadPost/Main/Comment/CommentBox.module.scss
  components/ReadPost/Main/Comment/CommentBox.tsx
  components/ReadPost/Main/Comment/CommentContainer.module.scss
  components/ReadPost/Main/Comment/CommentContainer.tsx
  components/ReadPost/Main/Comment/CommentSubmitForm.module.scss
  components/ReadPost/Main/Comment/CommentSubmitForm.tsx
  components/ReadPost/Main/Comment/Reply.module.scss
  components/ReadPost/Main/Comment/Reply.tsx
  components/ReadPost/Main/MainContainer.module.scss
  components/ReadPost/Main/MainContainer.tsx
  components/ReadPost/Main/ProfileContainer.module.scss
  components/ReadPost/Main/ProfileContainer.tsx
  components/ReadPost/hooks/useImageControl.ts
  components/ReadPost/hooks/useKebabState.ts
  package-lock.json
  package.json
  public/icons/filled-image-index.svg
  public/icons/image-index.svg
  public/icons/next-button.svg
  public/icons/previous-button.svg
  queries/usePostQueries.ts
  stores/useModalStore.ts
  styles/global-styles/font.scss
  styles/global-styles/global.scss
  styles/global-styles/theme.css
  utils/calculateDisappearTime.ts
Labels: Task, 기능구현, 리팩토링

#104 피드페이지 필터링모달 카테고리 해결 중
  app/feed/_components/FilteringModal/FilteringModal.module.scss
  app/feed/_components/FilteringModal/FilteringModal.tsx
  components/Category/CategoryFiltering.module.scss
  components/Category/CategoryFiltering.tsx
  components/Category/SubCategoryFiltering.module.scss
  components/Category/SubCategoryFiltering.tsx
Labels: 버그

#105 back to top 버튼 제작
  apis/notification/getNotificationList.ts
  apis/notification/readNotification.ts
  apis/notification/readNotificationAll.ts
  app/mypage/_components/Comment/CommentItem.tsx
  app/mypage/_components/UpdateProfileModal/UpdateProfileModal.module.scss
  app/mypage/myPage.module.scss
  app/mypage/page.tsx
  app/signin/_hooks/useCreateUserForm.ts
  components/BackToTopButton/BackToTopButton.module.scss
  components/BackToTopButton/BackToTopButton.tsx
  components/GlobalNavigationBar/AlarmIcon.tsx
  components/GlobalNavigationBar/MenuBar.tsx
  components/GlobalNavigationBar/NotificationIcon.tsx
  components/GlobalNavigationBar/NotificationModal/NotificationItem.module.scss
  components/GlobalNavigationBar/NotificationModal/NotificationItem.tsx
  components/GlobalNavigationBar/NotificationModal/NotificationList.module.scss
  components/GlobalNavigationBar/NotificationModal/NotificationList.tsx
  components/GlobalNavigationBar/NotificationModal/NotificationModal.module.scss
  components/GlobalNavigationBar/NotificationModal/NotificationModal.tsx
  components/Modal/ModalContainer.tsx
  components/Post/PostItem.tsx
  components/Post/PostList.tsx
  public/icons/chevron-up-double-large.svg
  public/icons/chevron-up-double-small.svg
  queries/keys/notificationQueryKeys.ts
  queries/useNotificationQueries.ts
  stores/useModalStore.ts
  types/Notification.ts
Labels: Task, 기능구현, 리팩토링

#112 navbar 기능 연결
  apis/user/sign/signout.ts
  app/mypage/_components/UpdateProfileModal/UpdateProfileModal.tsx
  app/mypage/_components/UserProfile/UserProfile.module.scss
  app/mypage/_components/UserProfile/UserProfile.tsx
  app/mypage/_hooks/useUpdateUserProfileForm.ts
  app/mypage/page.tsx
  components/Avatar/Avatar.tsx
  components/Button/MonoButton.tsx
  components/GlobalNavigationBar/MenuBar.tsx
  components/GlobalNavigationBar/NotificationIcon.tsx
  components/GlobalNavigationBar/NotificationModal/NotificationItem.module.scss
  components/GlobalNavigationBar/NotificationModal/NotificationList.module.scss
  components/GlobalNavigationBar/NotificationModal/NotificationModal.tsx
  components/GlobalNavigationBar/ProfileModal/ProfileModal.module.scss
  components/GlobalNavigationBar/ProfileModal/ProfileModal.tsx
  components/GlobalNavigationBar/ProfileModal/_hooks/useSignout.ts
  components/Modal/ModalContainer.tsx
  components/Post/PostItem.module.scss
  components/Post/PostItem.tsx
  hooks/usePolling.ts
  public/images/default-user-image.svg
  stores/useModalStore.ts
  stores/useNotificationStore.ts
Labels: Task, 기능구현

#115 Feature/map clustering
  app/map/_components/Map/BlobMap.tsx
  app/map/_components/Marker/MarkerWithInfoWindow.module.scss
  app/map/_components/Marker/MarkerWithInfoWindow.tsx
  app/map/_components/Marker/Markers.tsx
  app/map/_deprecated/LiveMapGoogleMap.tsx
  package-lock.json
  package.json
Labels: Task, 기능구현

#116 맵 모바일 바텀시트 스타일링
  app/feed/Feed.module.scss
  app/feed/[postId]/page.tsx
  app/feed/page.tsx
  app/map/_components/Map/BlobMap.tsx
  app/map/_components/Marker/MarkerWithInfoWindow.tsx
  app/map/_components/Marker/Markers.tsx
  app/map/_components/SideBar/SideBar.module.scss
  app/map/_components/SideBar/SideBar.tsx
  app/map/_constants/mapOptions.ts
  app/map/_hooks/useControlBottomSheet.ts
  app/map/_hooks/useCreateForm.ts
  app/map/page.tsx
  components/Modal/WritePost/WritePost.tsx
  components/ReadPost/Header/ReadPostHeader.tsx
  components/ReadPost/Main/Comment/CommentBox.module.scss
  components/ReadPost/Main/Comment/CommentBox.tsx
  components/ReadPost/Main/MainContainer.tsx
  hooks/useUploadImage.ts
  package-lock.json
  package.json
  public/icons/line-horizontal.svg
  queries/usePostQueries.ts
Labels: 퍼블리싱

#120 feat: useCurrentLocationAddress (현재위치 상세주소)
  apis/map/getGeocodedAddress.ts
  app/map/_hooks/useCurrentLocationAddress.ts
  queries/keys/blobmapQueryKeys.ts
  queries/useBlobmapQueries.ts
Labels: 기능구현

#122 hotfix: userId->blobId
  apis/axios.ts
  apis/oauth/getOAuthData.ts
  apis/user/mypage/deleteProfileImage.ts
  apis/user/mypage/getUserBookmarkList.ts
  apis/user/mypage/getUserCommentList.ts
  apis/user/mypage/getUserDetail.ts
  apis/user/mypage/getUserPostList.ts
  apis/user/sign/deleteUser.ts
  app/layout.tsx
  app/mypage/_components/Tab/TabList.tsx
  app/mypage/_components/UpdateProfileModal/UpdateProfileModal.module.scss
  app/mypage/_components/UpdateProfileModal/UpdateProfileModal.tsx
  app/mypage/_components/UserProfile/UserProfile.tsx
  app/mypage/_hooks/useUpdateUserProfileForm.ts
  app/mypage/page.tsx
  app/oauth/[provider]/page.tsx
  app/signin/_hooks/useCreateUserForm.ts
  app/signin/page.tsx
  app/user/[blobId]/page.tsx
  components/Avatar/Avatar.module.scss
  components/Avatar/Avatar.tsx
  components/CtaButton/CatButton.module.scss
  components/CtaButton/CtaButton.tsx
  components/CtaComponent/CtaComponent.module.scss
  components/CtaComponent/CtaComponent.tsx
  components/Footer/Footer.module.scss
  components/Footer/Footer.tsx
  components/GlobalNavigationBar/MenuBar.tsx
  components/GlobalNavigationBar/ProfileModal/ProfileModal.tsx
  components/Kebab.tsx
  components/Post/PostList.tsx
  components/ReadPost/Main/MainContainer.tsx
  components/ReadPost/Main/ProfileContainer.tsx
  package-lock.json
  package.json
  public/icons/CTA Explore.svg
  public/icons/CTA Write.svg
  public/icons/logo-ver2-small.svg
  queries/keys/userQueryKeys.ts
  queries/usePostQueries.ts
  queries/useUserQueries.ts
  stores/useOAuthStore.ts
  stores/userStore.ts
  types/User.ts
Labels: Task, 기능구현, 버그, 퍼블리싱

#123 이미지 없어도 업로드 가능, 모달에서 지정한 위치에 게시글 작성
  app/feed/page.tsx
  app/map/_components/Map/MiniMap.tsx
  app/map/_hooks/useCreateForm.ts
  components/Button/BlobButton.module.scss
  components/GlobalNavigationBar/MenuBar.tsx
  components/Modal/WritePost/WritePost.tsx
  hooks/useUploadImage.ts
Labels: Task, 기능구현

#125 Not found 페이지
  app/not-found.module.scss
  app/not-found.tsx
  public/icons/home.svg
  public/images/404.png
Labels: 퍼블리싱

#126 style: Search Bar Style
  app/map/_components/Autocomplete/AutoComplete.module.scss
  app/map/_components/Autocomplete/Autocomplete.module.scss
  app/map/_components/Autocomplete/Autocomplete.tsx
  app/map/_components/Autocomplete/AutocompleteMini.module.scss
  app/map/_components/Autocomplete/autocomplete.css
  public/icons/search-lens-color.svg
  public/icons/settings-04.svg
Labels: 퍼블리싱

#124 피드페이지 필터링 모달과 연결
  app/feed/_components/FilteringModal/FilteringModal.module.scss
  app/feed/_components/FilteringModal/FilteringModal.tsx
  app/feed/page.tsx
  components/Category/CategoryFiltering.module.scss
  components/Category/CategoryFiltering.tsx
  components/Category/SubCategoryFiltering.module.scss
  components/Category/SubCategoryFiltering.tsx
  components/CategoryBox.module.scss
  components/CategoryBox.tsx
  components/Modal/WritePost/WritePost.tsx
  components/Post/PostList.tsx
  package-lock.json
  package.json
  queries/usePostQueries.ts
  stores/useFilteringStore.ts
  stories/CategoryFiltering.stories.tsx
  stories/SubCategoryFiltering.stories.tsx
Labels: 기능구현

#130 모달 퍼블리싱, 카테고리 주석 처리
  app/map/_components/Map/MiniMap.module.scss
  app/map/_components/Map/MiniMap.tsx
  app/map/_hooks/useCreateForm.ts
  components/Button/BlobButton.tsx
  components/Modal/WritePost/PositionDetail.module.scss
  components/Modal/WritePost/PositionDetail.tsx
  components/Modal/WritePost/WritePost.module.scss
  components/Modal/WritePost/WritePost.tsx
Labels: 퍼블리싱

#131 feat: map marker api 연동
  apis/map/getMarkers.ts
  apis/map/getSidebarItems.ts
  app/map/_components/Map/BlobMap.tsx
  app/map/_components/Marker/Marker.module.scss
  app/map/_components/Marker/Marker.tsx
  app/map/_components/Marker/MarkerHighlight.module.scss
  app/map/_components/Marker/MarkerHighlight.tsx
  app/map/_components/Marker/MarkerWithInfoWindow.tsx
  app/map/_components/Marker/Markers.tsx
  queries/keys/blobmapQueryKeys.ts
  queries/useBlobmapQueries.ts
  stores/useMapStore.ts
  stories/Marker.stories.ts
  stories/MarkerHigilight.stories.ts
Labels: 기능구현

#129 로딩 시 로딩스피너 추가
  app/map/_deprecated/LiveMapAdvanced.tsx
  app/map/_deprecated/LiveMapGoogleMap.tsx
  app/mypage/_components/UpdateProfileModal/UpdateProfileModal.tsx
  app/mypage/_components/UserProfile/UserProfile.tsx
  app/oauth/[provider]/AwaitSignin.module.scss
  app/oauth/[provider]/page.tsx
  components/Comment/CommentList.tsx
  components/Comment/CommentedPostItem.tsx
  components/GlobalNavigationBar/NotificationModal/NotificationList.tsx
  components/Loading/Loading.module.scss
  components/Loading/Loading.tsx
  components/Post/PostList.tsx
  components/ReadPost/Main/Comment/CommentBox.tsx
Labels: 기능구현

#133 랜딩페이지 완성
  app/LandingPage.module.scss
  app/landing/ScrollWrapper.tsx
  app/landing/Section1.tsx
  app/landing/Section2.tsx
  app/landing/Section3.tsx
  app/landing/Section4.tsx
  app/landing/animations/fadeInAnimation.ts
  app/mypage/_components/UpdateProfileModal/UpdateProfileModal.module.scss
  app/mypage/_components/UpdateProfileModal/UpdateProfileModal.tsx
  app/page.tsx
  components/Button/BlobButton.module.scss
  components/GlobalNavigationBar/NotificationModal/NotificationItem.tsx
  components/GlobalNavigationBar/NotificationModal/NotificationList.module.scss
  components/GlobalNavigationBar/NotificationModal/NotificationList.tsx
  components/GlobalNavigationBar/NotificationModal/NotificationModal.tsx
  components/shared/Logo.module.scss
  hooks/useScrollAnimation.ts
  package-lock.json
  package.json
  public/fonts/bagel-fat-one/BagelFatOne-Regular.ttf
  public/fonts/bagel-fat-one/Bagel_Fat_One.css
  queries/useUserQueries.ts
Labels: Task, 리팩토링, 퍼블리싱

#136 전역으로 현위치 관리, mini버전 자동완성 퍼블리싱
  app/map/_components/Autocomplete/Autocomplete.tsx
  app/map/_components/Autocomplete/AutocompleteMini.module.scss
  app/map/_components/Map/MiniMap.tsx
  app/map/_hooks/useCreateForm.ts
  components/Modal/WritePost/WritePost.module.scss
  stores/useMapStore.ts
Labels: Task, 기능구현, 퍼블리싱

#135 사이드바 및 바텀시트 퍼블리싱
  apis/map/getMarkers.ts
  apis/post/deleteComment.ts
  apis/post/deletePost.ts
  apis/post/updateCommentReport.ts
  apis/post/updatePostReport.ts
  app/feed/page.tsx
  app/map/_components/Marker/Markers.tsx
  app/map/_components/SideBar/BottomSheet.module.scss
  app/map/_components/SideBar/BottomSheet.tsx
  app/map/_components/SideBar/Order.module.scss
  app/map/_components/SideBar/Order.tsx
  app/map/_components/SideBar/Post/PostItem.module.scss
  app/map/_components/SideBar/Post/PostItem.tsx
  app/map/_components/SideBar/Post/PostList.module.scss
  app/map/_components/SideBar/Post/PostList.tsx
  app/map/_components/SideBar/SideBar.module.scss
  app/map/_components/SideBar/SideBar.tsx
  app/map/_hooks/useControlBottomSheet.ts
  app/map/page.tsx
  app/not-found.module.scss
  components/CategoryBox.tsx
  components/Kebab.tsx
  components/Modal/ModalContainer.module.scss
  components/ReadPost/Main/Comment/CommentContainer.tsx
  components/ReadPost/Main/Comment/Reply.tsx
  components/ReadPost/Main/MainContainer.module.scss
  components/ReadPost/Main/MainContainer.tsx
  components/ReadPost/hooks/useReport.ts
  public/icons/chevron-down.svg
  public/icons/chevron-right-button.svg
  public/icons/settings-04.svg
  queries/useBlobmapQueries.ts
  stores/useFilteringStore.ts
  types/Post.ts
Labels: 퍼블리싱

#138 글쓰기모달 카테고리 퍼블리싱 & 데이터 추가
  app/feed/_components/FilteringModal/FilteringModal.module.scss
  app/feed/_components/FilteringModal/FilteringModal.tsx
  components/Modal/WritePost/WritePost.module.scss
  components/Modal/WritePost/WritePost.tsx
Labels: 퍼블리싱

#139 카테고리 완료
  app/LandingPage.module.scss
  app/landing/ScrollWrapper.tsx
  app/landing/Section1.tsx
  app/landing/Section2.tsx
  app/landing/Section3.tsx
  app/landing/Section4.tsx
  app/landing/animations/fadeInAnimation.ts
  app/map/_components/Autocomplete/Autocomplete.tsx
  app/map/_components/Autocomplete/AutocompleteMini.module.scss
  app/map/_components/Map/MiniMap.tsx
  app/map/_hooks/useCreateForm.ts
  app/mypage/_components/UpdateProfileModal/UpdateProfileModal.module.scss
  app/mypage/_components/UpdateProfileModal/UpdateProfileModal.tsx
  app/page.tsx
  components/Button/BlobButton.module.scss
  components/GlobalNavigationBar/NotificationModal/NotificationItem.tsx
  components/GlobalNavigationBar/NotificationModal/NotificationList.module.scss
  components/GlobalNavigationBar/NotificationModal/NotificationList.tsx
  components/GlobalNavigationBar/NotificationModal/NotificationModal.tsx
  components/Modal/WritePost/PostModalInput.module.scss
  components/Modal/WritePost/WritePost.module.scss
  components/Modal/WritePost/WritePost.tsx
  components/shared/Logo.module.scss
  hooks/useScrollAnimation.ts
  package-lock.json
  package.json
  public/fonts/bagel-fat-one/BagelFatOne-Regular.ttf
  public/fonts/bagel-fat-one/Bagel_Fat_One.css
  queries/useUserQueries.ts
  stores/useMapStore.ts
Labels: Task, 기능구현, 퍼블리싱

#137 fix: 댓글목록 클릭할 수 있도록 함
  components/Comment/CommentItem.tsx
Labels: 리팩토링

#144 blob 시간 문제, 에러처리, 메인 페이지 리뷰 반영하여 변경
  apis/axios.ts
  apis/post/deleteComment.ts
  apis/post/deletePost.ts
  apis/post/getFeed.ts
  apis/post/updateCommentReport.ts
  apis/post/updatePostReport.ts
  app/map/_components/SideBar/BottomSheet.tsx
  app/map/_components/SideBar/SideBar.tsx
  app/page.tsx
  components/Post/PostList.tsx
  components/ReadPost/Header/ReadPostHeader.tsx
  components/ReadPost/Main/Comment/Reply.tsx
  queries/usePostQueries.ts
  utils/calculateDisappearTime.ts
Labels: 버그

#146 자잘한것 수정
  app/map/_components/SideBar/Post/PostList.module.scss
  components/GlobalNavigationBar/NotificationModal/NotificationList.module.scss
  components/GlobalNavigationBar/NotificationModal/NotificationList.tsx
  components/Modal/WritePost/PositionDetail.module.scss
  components/Modal/WritePost/PositionDetail.tsx
  components/Modal/WritePost/WritePost.tsx
Labels: 기능구현, 리팩토링, 퍼블리싱

#147 남은시간 에러 수정, nav & 피드페이지 폰트 적용
  app/LandingPage.module.scss
  components/GlobalNavigationBar/TabItem.module.scss
  public/fonts/bagel-fat-one/BagelFatOne.css
  public/fonts/bagel-fat-one/ttf/BagelFatOne-Regular.ttf
  public/fonts/outfit/Outfit.css
  public/fonts/outfit/ttf/Outfit-SemiBold.ttf
  utils/calculateDisappearTime.ts
Labels: 버그, 퍼블리싱

#152 리드미 문서 작성
  README.md
Labels: 세팅
