Repository PROJECT-BLOB/front-end, pull requests merged in 2024-04, with the labels that each got.

#18 모달 레이아웃 및 폼 형식 생성
  app/map/_components/Modal.module.scss
  app/map/_components/Modal.tsx
  app/map/_hooks/useCreateForm.ts
  app/map/page.tsx
  stores/.gitkeep
  stores/useBlobModalStore.ts
Labels: Task, 기능구현

#19 feat: sign oauth 세팅
  apis/.gitkeep
  apis/axios.ts
  app/signin/_business-layer/OAuth.ts
  app/signin/page.tsx
  app/signup/page.tsx
Labels: 기능구현

#21 이미지 미리보기 및 취소, 제출 버튼 로직 작성
  app/map/_components/Modal.tsx
  app/map/_components/Modal/Modal.module.scss
  app/map/_components/Modal/Modal.tsx
  app/map/_components/ModalImage/ModalImage.tsx
  app/map/_hooks/useCreateForm.ts
  app/map/page.tsx
  public/images/.gitkeep
  public/images/default-image.png
Labels: Task, 기능구현

#25 마이페이지 user 관련 fetch 함수 생성
  apis/user/getUserBookmarkList.ts
  apis/user/getUserCommentList.ts
  apis/user/getUserPostList.ts
Labels: Task, 기능구현

#26 feat: api 작성
  apis/user/checkBlobId.ts
  apis/user/checkNickName.ts
  apis/user/createUser.ts
  apis/user/deleteUser.ts
  apis/user/updateBio.ts
Labels: Task, 기능구현

#27 유저 api 설계
  apis/user/deleteProfileImage.ts
  apis/user/updateNickname.ts
  apis/user/updateProfileImage.ts
  apis/user/updateProfileVisibility.ts
Labels: Task, 기능구현

#29 유저 로그아웃 설계
  apis/sign/signout.ts
  app/signin/page.tsx
  hooks/useRedirectSigninUser.ts
  stores/userStore.ts
Labels: 기능구현

#33 코드 리팩토링 및 debounce 기능 구현
  apis/user/getUserBookmarkList.ts
  apis/user/getUserCommentList.ts
  apis/user/getUserPostList.ts
  components/SearchBar.tsx
  hooks/useDebounce.ts
Labels: 기능구현, 리팩토링

#32 query-key-factory 라이브러리를 사용해서 React Query 관리
  apis/user/index.ts
  apis/user/mypage/deleteProfileImage.ts
  apis/user/mypage/getUserBookmarkList.ts
  apis/user/mypage/getUserCommentList.ts
  apis/user/mypage/getUserDetail.ts
  apis/user/mypage/getUserPostList.ts
  apis/user/mypage/updateNickname.ts
  apis/user/mypage/updateProfileImage.ts
  apis/user/mypage/updateProfileVisibility.ts
  apis/user/sign/checkBlobId.ts
  apis/user/sign/createUser.ts
  apis/user/sign/deleteUser.ts
  apis/user/sign/signout.ts
  app/layout.tsx
  app/signin/page.tsx
  app/signup/page.tsx
  queries/keys/userQueryKeys.ts
  queries/useUserQueries.ts
  queries/userQueries.ts
  utils/WrapperProvider.tsx
Labels: 기능구현

#38 로그인 페이지 퍼블리싱
  apis/axios.ts
  apis/oauth/getRedirectUrl.ts
  app/signin/Signin.module.scss
  app/signin/_business-layer/OAuth.ts
  app/signin/_components/SigninButton.module.scss
  app/signin/_components/SigninButton.tsx
  app/signin/page.tsx
  public/icons/.gitkeep
  public/icons/logo-BLOB.svg
  public/icons/logo-kakao.svg
  public/icons/logo-naver.svg
  styles/global-styles/reset.css
Labels: Task, 기능구현

#42 소셜 로그인 연동
  apis/axios.ts
  apis/oauth/getAccessToken.ts
  apis/oauth/getRedirectUrl.ts
  apis/user/mypage/getUserBookmarkList.ts
  apis/user/mypage/getUserCommentList.ts
  apis/user/mypage/getUserDetail.ts
  apis/user/mypage/getUserPostList.ts
  app/auth/[provider]/page.tsx
  app/layout.tsx
  app/signin/Signin.module.scss
  app/signin/_business-layer/.gitkeep
  app/signin/_business-layer/OAuth.ts
  app/signin/_components/SigninButton.module.scss
  app/signin/_components/SigninButton.tsx
  app/signin/page.tsx
  stores/useTokenStore.ts
Labels: Task, 기능구현

#55 자동완성 검색바 제작
  app/maptest/AutoComplete.tsx
  app/maptest/BasicMapAlpha.tsx
  app/maptest/page.tsx
  package-lock.json
  package.json
Labels: 기능구현

#56 라디오 버튼, 체크박스 컴포넌트 생성
  apis/oauth/getAccessToken.ts
  app/layout.tsx
  app/oauth/[provider]/page.tsx
  app/signin/_components/SigninButton.module.scss
  app/signin/_components/SigninButton.tsx
  app/signin/page.tsx
  components/Checkbox/Checkbox.module.scss
  components/Checkbox/Checkbox.tsx
  components/Checkbox/CheckboxList.tsx
  components/RadioButton/Radio.module.scss
  components/RadioButton/Radio.tsx
  components/RadioButton/RadioGroup.tsx
  public/icons/checkbox-already-selected.svg
  public/icons/checkbox-disabled.svg
  public/icons/checkbox-indeterminated.svg
  public/icons/checkbox-selected.svg
  public/icons/checkbox-unselected.svg
  public/icons/logo-google.svg
  public/icons/radio-active.svg
  public/icons/radio-default.svg
  public/icons/radio-hover.svg
  public/icons/radio-mouse-down.svg
  public/icons/radio-mouse-up.svg
  stores/useTokenStore.ts
  stories/Checkbox.stories.ts
  stories/Radio.stories.ts
Labels: Epic, Task, 기능구현, 퍼블리싱
